### ISSUE TITLE
tempfile 3.0.9 raises the MSRV

### ISSUE THREAD

**Issue by asomers** [Stebalien/tempfile#100]
The latest release of tempfile raised its MSRV.  That's fine to do, but you should bump your minor version when you do that.  Otherwise it breaks downstream builds.  Would you please consider yanking 3.0.9 and renaming it 3.1.0?

https://github.com/nix-rust/nix/runs/158960516

**Comment by Stebalien** [comment]
I'll yank it when we cut a 3.1.0 (pending). I have a habit of abusing patch releases as most projects I work on are sub 1.0.

Aside: Rust 1.30 was released 8 months ago. Depending on old compilers is a massive pain for library maintainers.

**Comment by Stebalien** [comment]
Done.

**Comment by asomers** [comment]
Thanks.

**Comment by AndriusA** [comment]
Didn't want to open a separate issue as with move to 3.1.0 this gets resolved anyway, but as per Cargo reference:

>>> An update is allowed if the new version number does not modify the *left-most non-zero digit* in the major, minor, patch grouping. <...> If instead we had specified the version string as ^1.0, cargo should update to 1.1 if it is the latest 1.y release, but not 2.0.

Ran into this issue was another library I was depending on had `tempfile = "3.0"` and 3.1 got picked up despite some apparently breaking changes..

**Comment by Stebalien** [comment]
Updating the minimum rust version is not an API-breaking change. Unfortunately, cargo doesn't have a way to specify the minimum rust version yet.

**Comment by AndriusA** [comment]
Of course, and updating minor version is for backwards-compatible changes, so only something to bear in mind: using 0 as minor version makes it difficult for a dependant to lock the library to that minor version, while using any other number does.

The reason for yanking 3.0.9 and publishing as 3.1.0 seemed to be exactly that in the above discussion, but feel free to disregard

**Comment by Stebalien** [comment]
> Of course, and updating minor version is for backwards-compatible changes, so only something to bear in mind: using 0 as minor version makes it difficult for a dependant to lock the library to that minor version, while using any other number does.

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#tilde-requirements

> The reason for yanking 3.0.9 and publishing as 3.1.0 seemed to be exactly that in the above discussion, but feel free to disregard

You're right. While updating the minimum rust version isn't _technically_ an API-breaking change, it still (unfortunately) breaks some users so updating it in a _patch_ release just isn't nice (hence the yank). That "patch" release also included new features so it really should have been a minor release anyways.

**Comment by apoelstra** [comment]
> Updating the minimum rust version is not an API-breaking change.

I'm really trying to understand the logic behind this statement but I cannot. How is breaking compilation *not* an API-breaking change?

**Comment by Stebalien** [comment]
The rust compiler/standard library is just another dependency and updating the minimum minor version of a dependency is not a breaking change. An API-breaking change implies mandatory code changes in downstream packages. 

The only tricky part here is that cargo doesn't provide a way to specify the minimum rust version. My current solution to this is simply: stay several releases behind and hope that people upgrade in a reasonable time frame. Given that rustup is considered the official way to install rust, this is a pretty reasonable assumption.

**Comment by elichai** [comment]
I disagree that the compiler is just another dependency.
and as long as libstd is shipped as binary blobs with the compiler so the same for that.

People are using rust compilers from distribution releases (aka debian, arch etc.) 
Some want bootstrapibility using guix: https://guix.gnu.org/blog/2018/bootstrapping-rust/

Changing the required compiler version should be a breaking change and require a major bump

**Comment by Stebalien** [comment]
You're free to disagree, but that doesn't change the fact that bumping the minimum rust version does not change the API and is therefore not an API breaking change.

* API breaking changes require downstream code changes and will be signaled with a major version bump. Major version bumps cause _major headaches_ for downstream users as they'll often end up pulling in multiple conflicting versions of the same library due to transitive dependencies.
* Updating the MSRV is also definitely not a bug fix and should have been communicated with a minor release (which why I yanked the patch release).

I'm not aware of any rust projects that consider MSRV updates to be API breaking.

> People are using rust compilers from distribution releases (aka debian, arch etc.)

* Arch has a policy of updating to the latest release ASAP and absolutely refuses to support users who don't stay up to date.
* Rust doesn't backport security fixes to previous releases and Debian users should probably use rustup.

**Comment by apoelstra** [comment]
Everything in the rust-bitcoin ecosystem considers it a breaking change to break compilation. The same appears to be true of crates such as byteorder, serde, time, etc., which have been extremely reliable and never broken our build with minor releases. From my view, this npm culture of constant breakage seems mostly limited to the web-focused part of the Rust community.

Elichai listed several reasons that people will be using older compilers. The Arch model is not appropriate for high-assurance software, which is exactly the sort of software that people should be writing in Rust. (I routinely - 2 or 3 times a year - cannot start my X server after Arch updates.)

**Comment by BurntSushi** [comment]
No, `byteorder` does not have such a policy. `serde` doesn't either, although in practice, both crates remain pretty conservative. For `byteorder` and other crates I maintain, especially core crates, I try to keep MSRV changes pretty conservative, and do them in minor version bumps. But I, and many others, generally do not consider them API breaking changes requiring a major semver version bump.

This discussion is more of an ecosystem wide discussion, and has been ongoing in other places. Most prominently: https://github.com/rust-lang-nursery/api-guidelines/issues/123

> From my view, this npm culture of constant breakage seems mostly limited to the web-focused part of the Rust community.

This is really just completely inappropriate and is going to be counter productive. The only purpose commentary like this serves is to put folks on the defensive. Please don't do it.

**Comment by apoelstra** [comment]
> The only purpose commentary like this serves is to put folks on the defensive. Please don't do it.

Ok. I'm sorry.
