### ISSUE TITLE
what this error: help: a similar path exists: `self::tempfile`

### ISSUE THREAD

**Issue by jinfagang** [Stebalien/tempfile#103]
```
error[E0432]: unresolved import `tempfile`
  --> src/iota/view.rs:17:5
   |
17 | use tempfile::tempdir;
   |     ^^^^^^^^ help: a similar path exists: `self::tempfile`

warning: unused import: `command::Operation::Insert`
 --> src/iota/command.rs:3:5
  |
3 | use command::Operation::Insert;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: unused import: `std::path::Path`
 --> src/iota/view.rs:3:5
  |
3 | use std::path::Path;
  |     ^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `iota-editor`.

```

I am new to rust, does anyone knows what this means?

**Comment by Stebalien** [comment]
You may need to add "tempfile" to your Cargo.toml:

https://doc.rust-lang.org/cargo/guide/dependencies.html#adding-a-dependency

---

However, without more context, I can only guess.

**Comment by jinfagang** [comment]
@Stebalien  thanks for your reply. It just need to adding something like this and warning gone:

```
use self::tempfile
```

and I don't know why, why should adding a self::

**Comment by Stebalien** [comment]
I'm really not sure. You'll have to ask that question on the forums (discuss.ipfs.io).

**Comment by yfractal** [comment]
I think Rust's meaning is:

"I don't know how to find the `tempfiile`, but I fond a similar one which belongs to current package, so maybe you want use this one?"

**Comment by yzhong52** [comment]
Have you found an answer to this? I also notice that I have to add this to a few external dependencies. For examples:

```
use self::rstest::*;
```

```
use self::num::Zero;
```
