### ISSUE TITLE
remove_dir_all caret dependency is incompatible with tempfile MSRV

### ISSUE THREAD

**Issue by str4d** [Stebalien/tempfile#120]
The recent 0.5.3 release of the `remove_dir_all` crate bumped its effective MSRV to 1.40.0, and as now documented in https://github.com/XAMPPRocky/remove_dir_all/issues/21#issuecomment-649295073, the crate only supports the latest Rust version. However, the `remove_dir_all` crate is specified as a (default) caret dependency of `tempfile`:

https://github.com/Stebalien/tempfile/blob/6fe7f2c4b270c9766580010ba842e59bda9a1cf3/Cargo.toml#L22

This automatically selects 0.5.3, breaking `tempfile`'s MSRV of 1.32.0.

`tempfile` should either pin with `=0.5.2` until its MSRV reaches 1.40.0 (and always pin specific versions going forward, as caret dependencies may similarly break in future), or remove the `remove_dir_all` dependency.

**Comment by Stebalien** [comment]
It's about time to bump the MSRV anyways. 1.40 is 6 months old at this point.
