### ISSUE TITLE
Builder option to avoid cleanup on Drop

### ISSUE THREAD

**Issue by Mark-Simulacrum** [Stebalien/tempfile#122]
rustc has a `-Csave-temps` option that is intended for debugging (or other cases where temporary file access is useful).

We used to have code like this, but it behaved incorrectly in the presence of panics in the intermediary code. It would be nice to have a boolean flag on the builder that would let us do something like `.cleanup(opts.save_temps)` and that would create a TempDir which doesn't delete itself on Drop.

For now we've [implemented](https://github.com/rust-lang/rust/pull/75315) this in rustc itself atop TempDir, but upstreaming it would be more convenient API wise.

```rust
let tmpdir = ...;

// a bunch of code runs, using tmpdir

if opts.save_temps {
    let _ = tmpdir.into_path();
}
```

**Comment by Stebalien** [comment]
Sounds like a good feature.

**Comment by ethanuppal** [comment]
As a comment (and a bump on this), it might be instructive to look at Prof. Adrian Sampson's implementation of a temporary directory (https://github.com/calyxir/calyx/pull/2072); I had originally used a `TempDir`, but as no "keep directory" option was available, he opted to create a new abstraction for it.

**Comment by Stebalien** [comment]
Issue with more discussion here: https://github.com/Stebalien/tempfile/issues/194#issuecomment-2004613455
