### ISSUE TITLE
Depend on remove_dir_all 0.6

### ISSUE THREAD

**Issue by dvtomas** [Stebalien/tempfile#129]
I'm removing duplicate dependencies from my project, and remove_dir_all 0.5 (tempfile) vs 0.6 (others) is one of them

**Comment by Stebalien** [comment]
Note: This is currently blocked because `remove_all_dirs` 0.6+ adds a dependency on rayon, and I'm strongly against having a temporary file library launch new threads.

**Comment by messense** [comment]
Is `remove_dir_all` still needed? Cargo recently removed it and `std::fs::remove_dir_all` shows better performance: https://github.com/rust-lang/cargo/pull/11333

**Comment by Xaeroxe** [comment]
Resolved in #207. Also, `remove_dir_all` no longer requires `rayon`.

**Comment by stanislav-tkach** [comment]
By the way, there is a race condition in old (<0.8.0) versions of the `remove_dir_all` library, so it would be nice to either update or remove this crate.

**Comment by Xaeroxe** [comment]
Changed my mind, switched to removing it in #208

**Comment by adumbidiot** [comment]
Was https://github.com/rust-lang/rust/issues/29497 worked around?
