### ISSUE TITLE
NamedTempFile cannot persist to another NamedTempFile on Windows

### ISSUE THREAD

**Issue by acheronfail** [Stebalien/tempfile#131]
I have tests in my application which create temporary files, write to them, and then persist them. These tests fail on Windows with a Permission Denied error.

A small reproducible example is:

```rust
use std::io::Write;
use std::fs;

fn main() {
    let mut t1 = tempfile::NamedTempFile::new().unwrap();
    let mut t2 = tempfile::NamedTempFile::new().unwrap();

    t1.write_all(b"Hello, World!").unwrap();
    t2.write_all(b"Another file").unwrap();

    let t1_path = t1.path().to_owned();
    let t2_path = t2.path().to_owned();
    t1.persist(&t2.path()).unwrap();

    println!("t1: {}", fs::read_to_string(&t1_path).unwrap());
    println!("t2: {}", fs::read_to_string(&t2_path).unwrap());
}
```

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PersistError { error: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }, file: NamedTempFile("C:\\Users\\ACHERO~1\\AppData\\Local\\Temp\\.tmptOXOzo") }', src\main.rs:13:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\tmp.exe` (exit code: 101)
```

Is this the intended behaviour? I am unfamiliar with Windows development in general, and by the looks of the other issues here it seems permissions errors aren't exactly uncommon.

**Comment by Stebalien** [comment]
Yes, that's normal. On windows, you can't overwrite an open file
(persist t1 over t2). What's your use-case?

**Comment by acheronfail** [comment]
> On windows, you can't overwrite an open file

I literally just figured this out maybe a minute before you replied!
By dropping the `File` object it's fixed.

> What's your use-case?

My application performs an atomic replacement of a file. My specific use-case for this issue was during my unit tests, where I create "fake" files with `tempfile`, and then the app proceeds to create its own temp files (again with this crate) and tries to `.persist()` over them.

The issue was that I hadn't closed the `File`, so this is my fault, not the crate's!

**Comment by Stebalien** [comment]
I'm glad you found the issue. Windows... takes some getting used to (although, honestly, the extra control over file sharing between applications is actually kind of nice).
