### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by djc** [Stebalien/tempfile#136]
Would be nice to get a new release out that has all the updated dependencies.

**Comment by benesch** [comment]
@Stebalien this would be much appreciated, if you've got the time!

**Comment by davidpdrsn** [comment]
rand 0.8 is also out. Would be nice to get that in as well. I don't mind making a PR for it but there are already a few PRs around updating dependencies. Not sure what the status of those are.

**Comment by benesch** [comment]
@davidpdrsn I’m pretty sure that the rand 0.8 bump landed in https://github.com/Stebalien/tempfile/commit/b3142a158605ba6107644018a578a917ee3f6f54, unless there’s something I’m not seeing.

**Comment by Stebalien** [comment]
I will try to get to this tonight (want to make sure everything is in order first).

**Comment by benesch** [comment]
> I will try to get to this tonight (want to make sure everything is in order first).

That would be fantastic! Thanks, @Stebalien!

**Comment by Stebalien** [comment]
3.2.0 has been published. Thanks for your patience.

**Comment by benesch** [comment]
Thank _you_ for maintaining such a foundational part of the Rust ecosystem @Stebalien! I know it can be a pretty thankless task, but it's very much appreciated!
