### ISSUE TITLE
Add non-clobbering persist method

### ISSUE THREAD

**Issue by untitaker** [Stebalien/tempfile#14]
I'm considering depending on tempfile for https://github.com/untitaker/rust-atomicwrites. While NamedTempFile would fit my purposes, I fear that you might decide to improve security by e.g. keeping an fp open that tracks renames, so that you can remove the file even if renamed.

Could you clarify whether my usecase is valid for this library?

**Comment by Stebalien** [comment]
I'd love to do that but I can't so you should be safe. Regardless, you can always `mem::forget` the `NamedTempFile` object to prevent cleanup. Also, does `NamedTempFile::persist` not work for you?

**Comment by untitaker** [comment]
@Stebalien I do want auto-cleanup in situations where the rename fails.

**Comment by Stebalien** [comment]
> I do want auto-cleanup in situations where the rename fails.

Rename and then `mem::forget` if and only if the rename succeeds.

However, again, does `NamedTempFile::persist` not work for you?

**Comment by untitaker** [comment]
I want to close the file before renaming, so I'd need to either drop or forget before knowing whether the rename will succeed.

`persist` doesn't have all features I want. Concretely I want to atomically assert that the target file doesn't exist. I do that with `link` and `unlink` in `atomicwrites`.

**Comment by untitaker** [comment]
But yes, I guess this issue is fixed. Thanks!

**Comment by Stebalien** [comment]
> I want to close the file before renaming

Why? This shouldn't be necessary unless you want to try to make guarantees in the presence of buggy unsafe code but you can't do that anyways.

**Comment by untitaker** [comment]
For some reason I assumed Rust had an internal buffer (like Python does).

**Comment by untitaker** [comment]
@Stebalien FWIW, your advice wasn't applicable for me I think:

* move-before-close is not allowed under Windows
* `mem::forget` leaks memory, does not just free the struct without calling drop

**Comment by Stebalien** [comment]
You're right about `mem::forget`. I forgot that `NamedTempFile` contains a internal `PathBuf`. How about a non-clobbering persist method?

**Comment by Stebalien** [comment]
Does this work for you: https://github.com/Stebalien/tempfile/commit/848f5ecb51662b3bd091e378bc8cfea6e6b56730

**Comment by untitaker** [comment]
Ahh, I don't need to move the tempdir to the target path at all, I just want it to persist. `persist` and `persist_noclobber` is exactly what I am trying to implement, but cross-platform and without unsafe code on posix: https://github.com/untitaker/rust-atomicwrites/blob/master/src/lib.rs

**Comment by Stebalien** [comment]
OK, then I really don't think NamedTempFile is the right choice for you. Really, the only thing you should be doing with the temporary file (while owned by the NamedTempFile object) is reading/writing.
