### ISSUE TITLE
Feature request: Function to keep the file until the main process exits.

### ISSUE THREAD

**Issue by wucke13** [Stebalien/tempfile#140]
I would like to be able to create a file, which is used by child processes. However, I do not want to carry around the file handle all the time to avoid running it's destructor. Neither do I want to leak the file completely, once my main process exits (and thus all child processes as well) I would like to have the file deleted. So I want to allow for the file to get a static lifetime but have it cleaned up eventually.

**Comment by Stebalien** [comment]
There is no reliable way to do this in rust (cross platform, at least). In general, it's possible to use libc's "atexit" function, but that tends to be very brittle and error prone.

The best solution here would be to:

1. Open a named temporary file.
2. Start your child processes and wait for them to open the temporary file.
3. Close the named temporary file.

* On unix, the file will be unlinked immediately.
* On windows, the file will be unlinked when the last handle is closed.

However, any process still using the file will continue to be able to use it.

Alternatively, consider creating an application wide temporary directory.
