### ISSUE TITLE
std:io:copy not working for tempfiles

### ISSUE THREAD

**Issue by nimr0d** [Stebalien/tempfile#142]
Copying a tempfile does not work for me, while it does work for other types of files. I'm not familiar enough with how this works to understand why there would be a difference. I'm using linux.

**Comment by Stebalien** [comment]
I'm going to need to know a lot more:

- How did you create the temporary file?
- What code failed?
- What was the error message?

etc.

A link to the exact code in question would help quite a bit.

**Comment by nimr0d** [comment]
`   let mut dest_file = OpenOptions::new().write(true).create(true).append(true).open("some path")?;

    let mut tmp_file = tempfile::tempfile()?;
    tmp_file.write_fmt(format_args!("test"))?;
    println!("{}", tmp_file.metadata()?.len());
    let num_bytes = std::io::copy(&mut tmp_file, &mut dest_file)?;
    println!("{}", num_bytes);`

The output is 4 and 0. There is no error message. It creates a new file and appends 0 bytes to it.

**Comment by Stebalien** [comment]
After you write to the temporary file, the file "cursor" well be at the end. You need to seek back to the beginning before you can copy.
