### ISSUE TITLE
Build failed: No such file or directory (os error 2) 

### ISSUE THREAD

**Issue by cypherchabon** [Stebalien/tempfile#152]
I am trying to run on **Linux** a third party code, which makes use of this crate and I get the following error:

```
thread 'main' panicked at 'Build failed: No such file or directory (os error 2)', rid_build.rs:29:26
```
Error refers to the following line of code:

```rust
let tmp_dir = tempdir().context("Failed to create tmpdir")?;
```
Here I share some more code to give some context:

```rust
...
...
use tempfile::tempdir;

pub fn run_gen(
    ...
    ...
    let tmp_dir = tempdir().context("Failed to create tmpdir")?;
    let ffi_config_file_path: PathBuf = tmp_dir.path().join("gen_config.yaml");
    let mut ffi_config_file: File = File::create(&config_file_path)
        .context(format!(
            "Unable to create config file at {:?}",
            &config_file_path.as_path()
        ))?;

    config_file
        .write_all(yaml_string.as_bytes())
        .context("Failed to write yaml config")?;

    ...
    ...

    tmp_dir.close().context("Unable to properly clean temp dir")
)
```

The version used is "3.2.0"
Linux distribution: Elementary OS 5.1.7

**Comment by Stebalien** [comment]
This library tries to create a temporary directory in whatever [std::env::temp_dir()](https://doc.rust-lang.org/std/env/fn.temp_dir.html) returns. If that directory doesn't exist, creating the temporary directory will fail.

Likely, your `TMPDIR` environment variable is set to a non-existent directory.

**Comment by cypherchabon** [comment]
I have TMPDIR correctly set. The problem must be something else.

**Comment by mtshrmn** [comment]
I'm experiencing the same issue but with a similar code. I print the path to stdout but the folder doesn't seem to be created.

**Comment by Stebalien** [comment]
1. Please try running your program under strace and post the logs so we can see what's happening.
2. What filesystem is `TMPDIR`?

**Comment by mtshrmn** [comment]
I was debugging the code and apparently I was accidently consuming the `TempDir`, so the directory was being deleted immidiatly. Furthermore, my issue is not related to this one. Sorry for hijacking it.
