### ISSUE TITLE
[Feature] Flag on tempdir to not delete the directory on `Drop`

### ISSUE THREAD

**Issue by Nukesor** [Stebalien/tempfile#169]
`TempDir` is often used in tests to get an isolated environment.

When tests fail, it's sometimes extremely helpful to look at the failed test's artifacts.
However, this would have to be achieved without necessarily aborting the test (via `Err` or `panic`).

For instance, it would be quite helpful to disable the `drop` if some suspicious, but not outright wrong, values are detected.
This would allow the test to finish as usual, but one can still take a look at what might have caused those values afterwards.

To easily achieve this, it would be nice to have some kind of flag to disable the dir removal functionality.

**Comment by Stebalien** [comment]
Closing as won't fix as:

1. This feature would add overhead & complexity.
2. It's unclear if it really "fits".
3. There are readily available workarounds.

See #171 for discussion.
