### ISSUE TITLE
Yank 1.1.2, publish 2.0.0

### ISSUE THREAD

**Issue by bvssvni** [Stebalien/tempfile#17]
Bumping a minor or patch number breaks downstream libraries when Cargo attempts to link two different versions of the same crate.

**Comment by bvssvni** [comment]
Should probably wait for https://github.com/rust-lang-nursery/rand/issues/81

**Comment by Stebalien** [comment]
In general, depending on two different versions of the same crate is perfectly legal (they are just treated as two different crates). What error are you running into?

**Comment by bvssvni** [comment]
Glutin is broken because it depends on tempfile and another version of kernel32-sys.

**Comment by bvssvni** [comment]
The problem with depending on two different versions of the same crate is that existing code breaks when you bump the minor version instead of the major version. See https://github.com/PistonDevelopers/piston/issues/931

**Comment by Stebalien** [comment]
Unless I'm mistaken, this issue is not related to crates. I believe the issue is that rustc/cargo don't handle linking to the same dynamic library (kernel32) twice well which I consider to be a bug in either cargo or rust. That's why I'm asking for the error.

**Comment by bvssvni** [comment]
I don't think the link problem is a bug in Cargo, but intended behavior.

There are several libraries that got problems, for example https://github.com/PistonDevelopers/image-png.

Error message:

```
native library `kernel32` is being linked to by more than one package, and can only be linked to by one package

  kernel32-sys v0.1.4
  kernel32-sys v0.2.0
```

**Comment by Stebalien** [comment]
I know it's intended but I don't think the devs saw this consequence so I plan on writing an RFC to fix it (that's why I was asking for the error). I'm not going to maintain two versions because one of my dependencies bumps its version.

**Comment by Stebalien** [comment]
Also, this should be fixed: https://www.reddit.com/r/rust/comments/3s5wd1/how_to_deal_with_the_kernel32sys_version_issue/
