### ISSUE TITLE
Support for Utf8Path TempFile and TempDir?

### ISSUE THREAD

**Issue by sunshowers** [Stebalien/tempfile#179]
Hi there --

I'm the primary maintainer of [camino](https://crates.io/crates/camino), a popular Rust library for UTF-8 paths. I'm wondering if you were interested in adding support for it to tempfile.

This could be behind an optional feature.

We could add:

* `Builder::utf8_tempfile`/`Builder::utf8_tempfile_in` and `NamedUtf8TempFile`
* `Builder::utf8_tempdir`/`Builder::utf8_tempdir_in` and `Utf8TempDir`

These methods could continue to return `io::Error`, and if conversion to UTF-8 isn't successful could return an `InvalidData` variant with more information in the payload, similar to [`canonicalize_utf8`](https://docs.rs/camino/latest/camino/struct.Utf8Path.html#method.canonicalize_utf8).

**Comment by sunshowers** [comment]
I wrote https://crates.io/crates/camino-tempfile, a wrapper around tempfile, which addresses this.

**Comment by Stebalien** [comment]
Hey, sorry, I completely missed this issue. However, your solution of providing a wrapper seems like the correct approach.
