### ISSUE TITLE
doc: lazy_static NamedTempFile fails to remove itself because destructor doesn't run

### ISSUE THREAD

**Issue by jtmoon79** [Stebalien/tempfile#183]
A `static ref NamedTempFile` initialized using [`lazy_static`](https://github.com/rust-lang-nursery/lazy-static.rs) fails to remove itself after program completion.

### Reproduction

1. note the contents of the temporary directory (e.g. `ls -ltr /tmp`)
2. run the following [Rust Code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=82b9329aa060b9df7abfc0b628a1f60e)
```rust
extern crate tempfile; // 3.3.0
use tempfile::NamedTempFile;

extern crate lazy_static; // 1.4.0
use lazy_static::lazy_static;

use std::io::Write;  // for `NamedTempFile.write_all`


lazy_static! {
    static ref NTF1: NamedTempFile = {
        let mut ntf = NamedTempFile::new().unwrap();
        ntf.write_all("foo".as_bytes());
        ntf
    };
}

fn main() {
    eprintln!("NTF1.path() {:?}", NTF1.path());
}
```
3. note the contents of the temporary directory (e.g. `ls -ltr /tmp`)
**_The temporary file printed by the program remains after program completion._**

**Comment by Stebalien** [comment]
This is known and, unfortunately, unfixable as destructors don't run for statics. See https://docs.rs/tempfile/latest/tempfile/#resource-leaking.

Improvements to the documentation are welcome.

**Comment by jtmoon79** [comment]
> Improvements to the documentation are welcome.

I'm new to generating rust documentation. What is the full command(s) you use to generate the documentation?

I forked and cloned and edited some docstrings. Then ran `cargo build` which succeeded.
But `rustdoc` fails.
```shell
$ pwd
~/Projects/tempfile

$ cargo build
...

$ rustdoc --version
rustdoc 1.61.0-beta.3 (2431a974c 2022-04-17)

$ rustdoc src/lib.rs --crate-name tempfile
error[E0432]: unresolved import `remove_dir_all`
  --> src/dir.rs:11:5
   |
11 | use remove_dir_all::remove_dir_all;
   |     ^^^^^^^^^^^^^^ maybe a missing crate `remove_dir_all`?

error[E0432]: unresolved import `fastrand`
 --> src/util.rs:1:5
  |
1 | use fastrand;
  |     ^^^^^^^^ no `fastrand` in the root

error[E0433]: failed to resolve: use of undeclared crate or module `cfg_if`
 --> src/file/imp/mod.rs:1:1
  |
1 | cfg_if::cfg_if! {
  | ^^^^^^ use of undeclared crate or module `cfg_if`

error: Compilation failed, aborting rustdoc
```

How can I preview my local documentation changes?

**Comment by jtmoon79** [comment]
@Stebalien could this crate allow running a destructor for statics?
https://github.com/mmastrac/linktime

My offhand design is to keep some global collection of statically created Temporary files (maybe a new `tempfile` API would be necessary for that), and then use the after-`main` destructor provided by `linktime` to remove those files.

**Comment by Stebalien** [comment]
That crate looks cool but I'd rather not integrate something like that directly into this library.

IMO, a better (and more general) solution would be a `static_drop` crate implementing a `StaticDrop` wrapper type. You'd write:

```rust
static TEMPFILE: LazyLock<StaticDrop<NamedTempFile>> = LazyLock::new(|| {
    StaticDrop::new(NamedTempFile::new().expect("failed to create temporary file"))
});
```

Where `StaticDrop` registers itself for static dropping in its constructor and deregisters itself in its destructor.
