### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by joshtriplett** [Stebalien/tempfile#198]
The current state in git has some really helpful new features, particularly the generic version of `NamedTempFile`. I'd love to build atop that. Would it be possible to get a new release of the current state?

Thank you for working on tempfile!

**Comment by Stebalien** [comment]
Done.

I apologize for taking so long on this.

**Comment by joshtriplett** [comment]
@Stebalien No problem. Life happens, and not everything is about code. Thank you for the release. :heart:
