### ISSUE TITLE
Why does TempFile not support access to the underlying File?

### ISSUE THREAD

**Issue by reem** [Stebalien/tempfile#20]
I don't care/want/need to persist the file since I am using it for testing, but I want to run operations that are defined on the File type specifically on the TempFile. I can make a PR for accessor methods if they are desired, but their absence seems intentional to me so I figured I'd ask first.

**Comment by Stebalien** [comment]
I swear I had a reason for this but I can't quite remember it. I think I did this to remain forwards compatible with rust in case extra methods that don't apply to tempfiles were added to `File` (this was back when `File` still had/had recently removed a path accessor method). However, there's actually no reason for `TempFile` to exist at all (it doesn't have a destructor) so I think I'll just replace it with a bare function (and remove `TempFile` in 2.0).

**Comment by Stebalien** [comment]
I've pushed a new version to git that replaces `TempFile` with a `tempfile()` function that returns normal `File` objects. Does this work for you?

**Comment by reem** [comment]
Oh, perfect, that's even better! I was doing this dance where I created another `File` using `NamedTemporaryFile` + `File::open(temp_file.path())` (this is just for simple testing don't worry I read the docs) but just using `tempfile()` is much better.
