### ISSUE TITLE
Request for help/advice on using tempfile

### ISSUE THREAD

**Issue by assarbad** [Stebalien/tempfile#200]
Hi,

folks, I recently worked on marcusbuffett/pipe-rename#59 to investigate and - _so far only partially_ - fix a Windows-specific issue in `renamer` (the name of the binary for the aforementioned project).

The way it works is to invoke an editor (configured by environment variable or passed by command line) on a temporary file that contains one file/path per line. That's where your project comes in, albeit currently hardcoded to the somewhat dated version `tempfile = "3.1.0"` in `Cargo.toml`.

Now the issue on Windows comes down to a sharing violation. And that sharing violation is based on the fact that `tempfile` uses a sharing mode naming all of read+write+delete, but Notepad (in my example the invoked editor) opens it with _just_ `read` [when attempting to write back the changed contents](https://github.com/marcusbuffett/pipe-rename/pull/59#issuecomment-1301462217). Failing to (re)open the file for writing with a sharing violation Notepad then will prompt to save the file in an alternative directory instead.

Any idea how to dodge the issue without changing the implementation of `tempfile`? Or do you see that as the only way? Quite frankly to me it seems like the only option left, but then I am only a beginner/intermediate Rustacean.

Thanks and with best regards,

Oliver

**Comment by Stebalien** [comment]
Use TempDir to crate a temporary directory, then put the file there. Unfortunately, windows won't really let you do it any other way.

**Comment by assarbad** [comment]
Thanks so much for your advice!

**Comment by assarbad** [comment]
@Stebalien I think providing a way to open a readonly handle to the temporary file with `reopen()` could actually resolve the issue. But still investigating. I'll update and possibly reopen if this turns out to be a viable option.

**Comment by Stebalien** [comment]
The delete permission may be an issue, but maybe not?

**Comment by assarbad** [comment]
Just tested a number of scenarios. Here's how I got a working combination:

```
#![allow(unused_imports)]
use tempfile::tempdir;
use std::fs::{File,OpenOptions};
use std::os::windows::fs::OpenOptionsExt;
use std::os::windows::io::{AsRawHandle, FromRawHandle, RawHandle};
use std::path::Path;
use std::io::{self, Write, BufReader, BufRead, Error};
use std::process::Command;

use windows_sys::Win32::Foundation::{HANDLE, INVALID_HANDLE_VALUE};
use windows_sys::Win32::Storage::FileSystem::{ReOpenFile, FILE_ATTRIBUTE_TEMPORARY, FILE_ATTRIBUTE_NORMAL, FILE_GENERIC_READ, FILE_GENERIC_WRITE, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_SHARE_DELETE, FILE_FLAG_DELETE_ON_CLOSE};

pub fn create(path: &Path, open_options: &mut OpenOptions) -> io::Result<File> {
    open_options
        .create_new(true)
        .read(true)
        .write(true)
        .share_mode(FILE_SHARE_READ | FILE_SHARE_WRITE)
        .custom_flags(FILE_ATTRIBUTE_TEMPORARY)
        .open(path)
}

pub fn reopen(file: &File, _path: &Path) -> io::Result<File> {
    let handle = file.as_raw_handle();
    unsafe {
        let handle = ReOpenFile(
            handle as HANDLE,
            FILE_GENERIC_READ,
            FILE_SHARE_READ | FILE_SHARE_WRITE,
            0,
        );
        if handle == INVALID_HANDLE_VALUE {
            Err(io::Error::last_os_error())
        } else {
            Ok(FromRawHandle::from_raw_handle(handle as RawHandle))
        }
    }
}

fn open_editor(tmpfile: &Path) -> io::Result<bool>
{
    let child = Command::new("C:\\Windows\\notepad.exe")
        .arg(tmpfile)
        .spawn()?;
    let output = child.wait_with_output()?;
    if output.status.success() {
        return Ok(true);
    }
    Ok(false)
}

fn main() {
    let dirname = tempdir().unwrap();
    let dirname = dirname.path();
    let filepath = dirname.join("tempfile.txt");
    let filepath = filepath.as_path();
    eprintln!("Temporary file path: {}", filepath.display());
    let tmpfile = create(filepath, &mut OpenOptions::new());
    let mut tmpfile = tmpfile.unwrap();
    writeln!(tmpfile, "Foo bar baz").unwrap();
    eprintln!("Opened temporary file");
    let readonly_tmpfile = reopen(&tmpfile, filepath);
    let readonly_tmpfile = readonly_tmpfile.unwrap();
    eprintln!("Opened temporary file again (readonly, sharing mode: read)");
    eprintln!("Dropping tmpfile");
    drop(tmpfile);
    open_editor(filepath).unwrap();
    eprintln!("Dropping readonly_tmpfile");
    drop(readonly_tmpfile);
}
```

Turns out the initial sharing mode must not contain contain `FILE_SHARE_DELETE` (i.e. only `FILE_SHARE_READ | FILE_SHARE_WRITE`). Creating the temporary file read/write is fine, though.

Then I use `ReOpenFile()` but with the previous sharing mode (`FILE_SHARE_READ | FILE_SHARE_WRITE`) _and_ opening read-only.

Then I `drop()` the original file handle, leaving just my second read-only handle there.

After that I can open Notepad using the way `renamer` would do it and it will succeed reading **and** also writing.

And the file gets deleted as would be expected per `FILE_ATTRIBUTE_TEMPORARY` ...

Unfortunately there's no way I could get this behavior with the way `tempfile` currently works as I have no way to influence the initial sharing mode, whereas I _would_ be able to call `ReOpenFile()` myself without much problem.
