### ISSUE TITLE
Overriding a file when using Builder

### ISSUE THREAD

**Issue by brsnik** [Stebalien/tempfile#202]
Getting the following error:

    Error: Custom { kind: AlreadyExists, error: PathError { path: "/tmp", err: Custom { kind: AlreadyExists, error: "too many temporary files exist" } } }

When creating a file using the `Builder`.

    #[tokio::main]
    async fn main() -> Result<(), Box<dyn Error>> {
        let file = Builder::new().prefix("testsock").rand_bytes(0).tempfile()?;
  
        Ok(())
    }

How can I override the file?

**Comment by Stebalien** [comment]
For now, you'd:

1. Create the file.
2. Call `NamedTempFile::from_parts` to create a wrapper that will auto-delete the file. Or just construct a `TempPath` from the path.

**Comment by kontsaki** [comment]
hello, what about making `PathError` public ?

**Comment by Stebalien** [comment]
Please file a new issue.
