### ISSUE TITLE
Release to fix errno feature error

### ISSUE THREAD

**Issue by Anton-4** [Stebalien/tempfile#223]
Hi,
Thanks for working on tempfile :heart:

We encountered the following error when using tempfile 0.3.4 with wasm:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/small-ci-user/.cargo/registry/src/github.com-1ecc6299db9ec823/errno-0.2.8/src/lib.rs:20:33
   |
20 | #![cfg_attr(target_os = "wasi", feature(thread_local))]
   |                                 ^^^^^^^^^^^^^^^^^^^^^
```
This was due to a dependency; rustix 0.36.9. Dependabot has already updated the version on the main branch so a new release is all that is required to fix this.

**Comment by LingMan** [comment]
@voigt `remove_dir_all` was already dropped with `tempfile` 3.4.0. Simply updating should be all that's needed.

/me would like a a new release for the `windows-sys` and `rustix` bumps.

**Comment by aldanor** [comment]
rustix 0.37+ is out, would be great to have a new version of tempfile released so the build errors like the one above (hopefully) stop popping for everyone.

**Comment by sunfishcode** [comment]
@Stebalien Would you be able to publish a new release?

Alternatively, would you like help maintaining this crate? I can't put a lot of time into it, but I could help, if you'd like. As a maintainer of rustix and various related things, I'm familiar with maintenance of these kinds of crates.

**Comment by Stebalien** [comment]
Done.
