### ISSUE TITLE
Is creating a new TempDir thread-safe?

### ISSUE THREAD

**Issue by starptr** [Stebalien/tempfile#233]
It looks like currently, if the filesystem is racey, then it is possible to call, for example, `tempfile::TempDir::new()` concurrently such that it generates 2 `TempDir` values with the same path. I am worried about this because unit tests run in parallel.

**Comment by Stebalien** [comment]
It's not possible. The underlying "create directory" function will fail if the directory already exists.

The unit tests aren't failing because the directory names have sufficient entropy to be unlikely to collide.
