### ISSUE TITLE
Add convenient method equivalent to`TempDir:new('foo')`

### ISSUE THREAD

**Issue by mamcx** [Stebalien/tempfile#249]
I want to remove the dependabot for https://github.com/advisories/GHSA-mc8h-8q98-g5hr and I miss the old `TempDir:new('foo')` call.

The available constructors have different semantics and the proposed solution is kinda verbose: `tempfile::Builder::new().prefix(prefix).tempdir()`

**Comment by Stebalien** [comment]
You need to specify a prefix for the tempdir name? Or do you just need to specify a location. If you need to specify a location, `TempDir::new_in(...)` should do it.

**Comment by Stebalien** [comment]
Hm. I don't think I'm on the same page. Could you explain _exactly_ what you're trying to do and the desired effect?

**Comment by mamcx** [comment]
The desired effect is to recover the behaviour of the old `Tempdir::new`, I think the equivalent now is `tempfile::Builder::new().prefix(prefix).tempdir()`?

It add + create a folder with the prefix...

**Comment by Stebalien** [comment]
I'll consider it, but a stronger motivation beyond "I want to do this" would be helpful. Personally, I usually care about _where_ my temporary files go, but rarely care about their names.

**Comment by Stebalien** [comment]
Yeah, that makes sense. My concern is that I could add `TempDir::with_prefix(prefix)`, but then what about `TempDir::with_prefix_in(prefix, directory)`? In retrospect, `new` on both `TempDir` and `NamedTempFile` should have always taken a prefix (costs the user nothing to specify one) but that ship has sailed.

Yeah, ok, I should probably just do it. Now to the question of names:

- `with_prefix` (`with_prefix_in`)
- `prefixed` (`prefixed_in`)
- `new_with_prefix` (`new_with_prefix_in`)
- `new_prefixed` (`new_prefixed_in`).

I'm thinking the first one.

**Comment by mamcx** [comment]
Yes `with_` sounds good.
