### ISSUE TITLE
NamedTempFile::persist_noclobber panicks on Android

### ISSUE THREAD

**Issue by neonphog** [Stebalien/tempfile#259]
Due to this assertion in rustix: [https://github.com/bytecodealliance/rustix/blob/v0.38.3/src/backend/libc/fs/syscalls.rs#L511](https://github.com/bytecodealliance/rustix/blob/v0.38.3/src/backend/libc/fs/syscalls.rs#L511)

**Comment by Stebalien** [comment]
cc @sunfishcode

**Comment by sunfishcode** [comment]
Thanks for the report! I've now submitted https://github.com/bytecodealliance/rustix/pull/892 with a fix.

**Comment by sunfishcode** [comment]
The rustix bug here is now fixed in rustix 0.38.21.

**Comment by neonphog** [comment]
Woot - android CI is now passing sans-workaround. Thanks @sunfishcode :raised_hands: - closing this.
