### ISSUE TITLE
Release-plz

### ISSUE THREAD

**Issue by 0xJepsen** [Stebalien/tempfile#268]
Would you be open to using release please for automatic version and release PRs. If you like i can give a good example of a yaml file for it. I would open a full pr but it needs some env variable like cargo-api token to auto push to crates. In my experience the tool has been a breeze to use and reduced our overhead while improving stability for downstream users. 
https://release-plz.ieni.dev/

**Comment by Stebalien** [comment]
I prefer to release manually so I can update the changelog, verify that there aren't any breaking changes, etc.

But thanks!

**Comment by 0xJepsen** [comment]
Release please uses [cargo semver](https://github.com/obi1kenobi/cargo-semver-checks) to automatically detect and increment semver, which is less error prone than doing it manually which improves stability for downstream users.

**Comment by sunfishcode** [comment]
cargo-semver-checks is a great tool, but at this time there are still a [lot of things it doesn't know about](https://github.com/obi1kenobi/cargo-semver-checks#will-cargo-semver-checks-catch-every-semver-violation).

**Comment by 0xJepsen** [comment]
No worries, just a suggestion! It made my life a lot easier thought id recommend it.
