### ISSUE TITLE
Option to use `remove_dir` only instead of `remove_dir_all`

### ISSUE THREAD

**Issue by mythi** [Stebalien/tempfile#270]
I'm looking to use `tempdir` to handle temporary dirs on Linux [configfs](https://www.kernel.org/doc/Documentation/filesystems/configfs/configfs.txt) that has a property that the kernel handles the file attributes upon rmdir/mkdir.

Because of that `remove_dir_all` gets an error from the kernel when it first tries to remove the file attributes and only after that the directory itself.

I could workaround this to handle dropping myself but I'd also prefer to rely on the automatic drop from the library.

**Comment by Stebalien** [comment]
I think you mean _files_, not attributes (well, attributes from the perspective of configfs). That's an interesting use-case but, IMO, outside the scope of this library.

**Comment by mythi** [comment]
Yes, _files_. I can understand the feedback, though
