### ISSUE TITLE
Clarify Builder::permissions documentation on defaults for temporary directories

### ISSUE THREAD

**Issue by Imberflur** [Stebalien/tempfile#284]
The [documentation](https://docs.rs/tempfile/3.10.1/tempfile/struct.Builder.html#method.permissions) notes:

> The permissions to create the tempfile or [tempdir](https://docs.rs/tempfile/latest/tempfile/struct.Builder.html#method.tempdir) with. This allows to them differ from the default mode of `0o600` on Unix.

I read this as tempdirs defaulting to `0o600`, but in the implementation it looks like this default is only applied for tempfiles, not tempdirs?

(sidenote: it looks like there was a suggestion in https://github.com/Stebalien/tempfile/issues/114 to make the default 0700 for directories)

**Comment by Stebalien** [comment]
Hm, you're right. It would be good to both fix those docs and document the default mode. Could you submit a patch to fix the docs?

I'd _like_ to change the default mode, but that'll require a 4.0 release. I've added it to the list (https://github.com/Stebalien/tempfile/issues/258).
