### ISSUE TITLE
Document minimum supported rust version

### ISSUE THREAD

**Issue by Susurrus** [Stebalien/tempfile#29]
Failed to build on 1.8.0, but succeeds on 1.9.0. This is part of `nix`'s desire to specify a minimum rust version.

It would be good to have this minimum version tested on all CI architectures.

**Comment by Stebalien** [comment]
Thanks for bisecting this. I'll document the minimum version (and test it). Out of curiosity, what failed in 1.8?

**Comment by Susurrus** [comment]
You need 1.8 for the `#[target.'cfg(...)']` syntax in Cargo.toml. And then you need 1.9 for the use of `len()` in `src/unistd.rs:516` (`OsStr::len()` was added in https://github.com/rust-lang/rust/issues/29453)

**Comment by Stebalien** [comment]
Thanks. I've updated the README and CI tests to reflect the new minimum version.
