### ISSUE TITLE
Builder Permissions not setting universal access

### ISSUE THREAD

**Issue by lancelui-amzn** [Stebalien/tempfile#295]
I am trying to set permissions for the temp folder as `0o777`, but `Builder::permissions` sets it to `0o755`. Can it not set write permissions? Currently using `fs::set_permissions` to do so as a work around.

On tempfile version 3.12.0 with Amazon Linux 2.

[playground demonstration](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=edaff3084ee26efea1fa622d855e88dc)

**Comment by Stebalien** [comment]
It obeys the umask, which is unavoidable (without an additional call to `chmod`) but should definitely be better documented. I.e., when you set `0o777`, you get `0o777 & ~0o022` (assuming your umask is the default `0o022`).

**Comment by Stebalien** [comment]
Hm. Actually, I _think_ it should obey the umask but we have a test that disagrees. Let me look at taht.

**Comment by Stebalien** [comment]
Ah, nvm. I misread the test. Yeah, it'll obey the umask and there's not much we can do about it (other than explicitly calling `fs::set_permissions` ourselves).

See https://docs.rs/tempfile/latest/tempfile/struct.Builder.html#unix
