### ISSUE TITLE
Feature request: Add a way to generate a random path without creating a file

### ISSUE THREAD

**Issue by smalis-msft** [Stebalien/tempfile#297]
Certain APIs take a file pat, but expect there to be no file at that path so that they can create it (e.g. [UnixListener::bind](https://doc.rust-lang.org/std/os/unix/net/struct.UnixListener.html#method.bind)). It would be handy to have a way to generate random paths to pass to functions like these, without having to go through the dance of making a NamedTempFile, extracting the path, and then deleting it.

**Comment by Stebalien** [comment]
See (`Builder::make`](https://docs.rs/tempfile/latest/tempfile/struct.Builder.html#method.make). Especially the example.

I'm very reluctant to implement [`tmpnam`](https://man7.org/linux/man-pages/man3/tmpnam.3.html) for safety reasons (see the warnings on the man page).
