### ISSUE TITLE
feature: `with_suffix` to correspond to `with_prefix`

### ISSUE THREAD

**Issue by Borgerr** [Stebalien/tempfile#298]
Stumbled upon while trying to wrangle some integration testing for a CLI tool, which expects a specific filetype. `with_prefix` adds a short string to the start of a file's name. We can alter this very cleanly by simply doing some plumbing for adding a short string to the end of the file's name, instead. `Builder` already has a `suffix` method which we can leverage for this.

**Comment by Stebalien** [comment]
Seems reasonable, I'm happy to review a patch.
