### ISSUE TITLE
Restore default permissions on persist (on Unix)

### ISSUE THREAD

**Issue by tbu-** [Stebalien/tempfile#30]
Like #2 and #3, it would be nice to get a normal file after calling `persist` on a `NamedTemporaryFile`. `NamedTemporaryFile` is opened with `0o600`, I'd expect to get a `0o644` file after that.

**Comment by Stebalien** [comment]
I'd probably use `libc::umask` to determine the correct permissions but that sounds like a good idea.

**Comment by Stebalien** [comment]
Actually, this is a bit tricky. What if the user changes the file mode while it's a temporary file?

**Comment by tbu-** [comment]
The same could be said for the attributes in #2 or #3.

Hmm. Maybe add a function that tells `tempfile` to not mess with the file when persisting?

**Comment by Stebalien** [comment]
It's now possible to configure the permissions when creating a temporary file.
