### ISSUE TITLE
[Question] Why use `Box<Path>` instead of `PathBuf`?

### ISSUE THREAD

**Issue by bicarlsen** [Stebalien/tempfile#302]
Why did you choose to store a `Box<Path>` instead of a `PathBuf`? [[ref](https://github.com/Stebalien/tempfile/blob/335d91d538953bb535f0839f4daced8d008d1dab/src/dir/imp/any.rs#L21)]

**Comment by Stebalien** [comment]
It saves a word of memory. Not exactly a huge deal, but it's something.

-  `PathBuf` is 3 words (length, capacity, pointer).
- `Box<Path>` is 2 words (length, pointer).
- 
E.g., see https://users.rust-lang.org/t/use-case-for-box-str-and-string/8295/4.

**Comment by bicarlsen** [comment]
Thanks!
