### ISSUE TITLE
Close NamedTempFile without deleting

### ISSUE THREAD

**Issue by jasonwhite** [Stebalien/tempfile#36]
Is there a way to close the file handle without deleting the actual file? On Windows, I have a problem where a child process cannot open the temporary file for reading because the file handle is open by the parent process, resulting in a sharing violation.
 
The child process (which I cannot change) is opening the file with *only* `FILE_SHARE_READ`, not `FILE_SHARE_READ | FILE_SHARE_WRITE`. According to the [Microsoft docs](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx), if `FILE_SHARE_WRITE` is not specified in the share mode and another process has the file open for writing, `CreateFile` will fail with a sharing violation. Thus, the only way to fix this is to close the file handle before spawning the child process.

**Comment by Stebalien** [comment]
If you can modify the child program, opening the file with shared access (`FILES_SHARE_*`) will fix this (NamedTempFile opens the file with shared access).

However, this does sound like a useful feature. The tricky part will be getting the API right as this is only an issue on Windows. For now, you might be better of using the tempdir crate instead as that won't force you to keep the file open.

One possible API would be to have a `TempPath` object:

```rust
pub struct TempPath(PathBuf);

impl Drop for TempPath {
    fn drop(&mut self) {
        fs::remove_file(self.0)
    }
}

impl Deref for TempPath {
    fn deref(&self) -> &Path {
        &*self.0
    }
}

// Other methods (like persist) and conversions. Also, a conversion back into `NamedTempFile`.

impl NamedTempFile {
    fn into_temp_path(self) -> TempPath {
        let NamedTempFileInner { path, file } = self.0.take().unwrap();
        drop(file);
        TempPath(path)
    }
}
```

Thoughts?

**Comment by jasonwhite** [comment]
Thanks for the fast reply!

I cannot change the child process unfortunately. (I'm generating a temporary response file to pass to Microsoft's `LIB.exe`.)

I like that `TempPath` API (or something like it).

I'd be happy to help code this up. (Or let me know if you'd rather jump on it.)

**Comment by Stebalien** [comment]
Let's hold off until #33 gets merged. Then yes, I'd love to welcome contributions (I have little free time at the moment, as much as I'd love an excuse to write some more rust).

**Comment by jasonwhite** [comment]
I've already mostly finished it actually, but will refactor things as necessary after that is merged.

**Comment by Stebalien** [comment]
If you'd like early feedback, feel free to make a PR now.
