### ISSUE TITLE
Support creating in-memory temporary files

### ISSUE THREAD

**Issue by Stebalien** [Stebalien/tempfile#5]
I know this is possible on linux and freebsd. I think it's possible on OS X and Windows. The real question is whether or not to make this a separate type (instead of just TempFile). Also, support a named variant? This would need to be a different type because we wouldn't use actual paths.

**Comment by Stebalien** [comment]
Doesn't work well on windows. You have to allocate the memory up front.

**Comment by milesgranger** [comment]
Hi @Stebalien 
I am working with a crate which can _only_ open files via string reference to a file's location. My application does hold any files on disk but receives them over the wire. As a work around I'm using your fantastic lib here to write these files to a tempfile long enough for this other lib to read in the file. 

It's quite a high traffic application so I really need a way to trick this lib into reading the file from memory and skip the intermediary writing to disk step. I _think_ the goal of this issue would have solved this problem. Could you point me in the right direction?

Thanks! :+1:

**Comment by milesgranger** [comment]
Maybe silly question, but if I have a `tmpfs` at `/dev` for example, could I do something like 
```rust
tempfile::tempdir_in("/dev")
```
and effectively create a file 'in memory' that way?

**Comment by Stebalien** [comment]
Use `/dev/shm`, it exists for this exact purpose (shared memory).
