### ISSUE TITLE
Undefined variables in documentation for TempDir::new_in

### ISSUE THREAD

**Issue by asomers** [Stebalien/tempfile#53]
The docs for `TempDir::new_in` refer to `tmpdir` and `prefix`, neither of which is an argument to the function.  `tmpdir` should probably be `dir`, but I'm not sure about `prefix`.  The mention of `prefix` should probably just be removed.
https://docs.rs/tempfile/3.0.2/tempfile/struct.TempDir.html#method.new_in

**Comment by KodrAus** [comment]
Ah that's right, you now manage the prefix through `Builder`.

@asomers would you like to submit a PR this fixes this up?
