### ISSUE TITLE
Compile error: cannot find function `create` in module `imp`

### ISSUE THREAD

**Issue by lynncyrin** [Stebalien/tempfile#54]
## Issue

Cant install a dependent library (`wasm-bindgen-cli`) due to compilation issues in `tempfile`

## Expected Result

`cargo install wasm-bindgen-cli` runs successfully 🙂

## Error Details

[traceback in ci](https://travis-ci.com/lynncyrin/heroku-buildpack-rust/jobs/123886046#L667)

formatted traceback:

```
error[E0425]: cannot find function `create` in module `imp`
  --> /{{ PATH }}/tempfile-3.0.2/src/file/mod.rs:98:10
   |
98 |     imp::create(dir.as_ref())
   |          ^^^^^^ not found in `imp`
help: possible candidate is found in another module, you can import it into scope
   |
1  | use dir::create;
   |
```

## Environment

- [For this Cargo.toml file](https://github.com/lynncyrin/galaxy-gen/blob/65672227ee8cfc4baa3c02fe4e8b0ffdf17d13d6/Cargo.toml)
- [With this build script](https://github.com/lynncyrin/heroku-buildpack-rust/blob/dfba3238becfe6297e2cde4eb30d8a6afbcf10a1/bin/compile)
- on ubuntu 18.04

(not sure which of those 3 points is most relevant)

**Comment by KodrAus** [comment]
Thanks for the report @lynncyrin!

Hmm this is a bit strange. It looks like [the target OS configurations](https://github.com/Stebalien/tempfile/blob/master/src/file/imp/mod.rs) aren't being picked up in your build for some reason. Could you be trying to compile `wasm-bindgen` using the `wasm32-unknown-unknown` target? `tempfile` doesn't have an implementation for that target so the `imp` module would end up empty.

**Comment by lynncyrin** [comment]
So I think whats going on here is that 

- `wasm-bindgen` compiles to the `wasm32-unknown-unknown` target so it can execute in web browsers
- whereas `wasm-bindgen-cli` compiles to the default target (that being the users current operating system?) because its meant to be a build system layer that runs in a different context than `wasm-bindgen` itself

So! I've figured out what my issue is, thanks for the assist @KodrAus !
