### ISSUE TITLE
Enhance `Builder` to accept as `prefix` or `suffix` any value that implements `AsRef<OsStr>`

### ISSUE THREAD

**Issue by cipriancraciun** [Stebalien/tempfile#58]
Currently the builder allows for `prefix` and `suffix` only `str`, which requires them to be UTF-8 valid.  However the underlying code, as the whole Rust standard library, would allow any `OsStr` to be used.

(If needed I can provide the patch.)

**Comment by cipriancraciun** [comment]
[I have made a comment on #60 that describes my use-case from which this request stemmed.]

Handling the breaking of the `Builder` interface can be as was described in #57

**Comment by KodrAus** [comment]
Thanks @cipriancraciun. One thing we could look at doing is changing the builder to use `OsStr` internally, and add some new `prefix_os(&OsStr)` and `suffix_os(&OsStr)`. That way we wouldn't have to break anything. There's a function internally called `tmpname` that currently uses the fact that the prefix and suffix are valid utf8 to efficiently generate a random name. In this new scheme, in the case where the prefix and suffix aren't valid utf8 we'd need a temporary string to write the random bytes into, but that's probably not going to be common.

**Comment by cipriancraciun** [comment]
@KodrAus Indeed after I wrote my comments I thought that an even easier way, without breaking any backwards compatibility is to introduce the methods as you've described them, and behind the scenes keep everything as `OsStr` (which can easily be obtained from a simple `str`).

----

Regarding the `create_helper` method, I saw that there are a few "assumptions" made about the UTF-8-ness of the inputs.  However one could create a string `OsString` and use it as a buffer.

Moreover on this subject, perhaps it would be a good idea to "export" the `create_helper` function (or a wrapper for it), which would just handle the "creation" (the retry loop with error handling), and receive all the "naming policy" as a generator.

For example:
````
fn create_temp <G, O, R> (generator : G, opener : O) -> io::Result<O>
    where G : Fn () -> io::Result<PathBuf>,
               O : Fn (PathBuf) -> io::Result<O>
````

In this way, if one needs any other "strange" extensions to `Builder` can just use this low-level function.  (The current code looks almost like this by having the `util::tmpname` do exactly what the "generator" would do.  (Also notice that the generator can issue errors.)

For example all my requested features could have just as easily been implemented by using this method.

----

You may ask:  what would be an use-case for such an "advanced" feature?

If one implements a system that heavily relies on temporary files (by having a large churn), and moreover with high concurrency (from multiple processes), currently using only one folder for the temporary files will be a bottle-neck, as in the end the kernel would just "synchronize" on this single point.  However if for example the generator function return randomly not only the names but also a set of folders (all on the same mount-point), then this "synchronization" bottle-neck is eluded.

(This use-case is not made-up, I had to rely on this pattern...)

**Comment by KodrAus** [comment]
@cipriancraciun Unfortunately we can't really use an `OsString` as a buffer, because it's platform specific so we don't really know anything about them and have a very narrow API for interacting with them.

I did play around with this [on a branch](https://github.com/KodrAus/tempfile/blob/feat/osstr-builder/src/util.rs#L9-L51) and it looks like we can support a fast guaranteed-utf8 random name generator along with a very slightly slower non-guaranteed-utf8 one. I think adding `OsStr` support to the builder would be a useful addition.

**Comment by KodrAus** [comment]
@Stebalien Do you have any thoughts on adding new methods to the builder that take `&OsStr` instead of `&str`, and internally figuring out whether we need to deal with non-UTF8 data or whether we can use the current implementation, [like in this patch](https://github.com/Stebalien/tempfile/compare/master...KodrAus:feat/osstr-builder)?

**Comment by Stebalien** [comment]
> This makes sense, unfortunately we can't really change the signature of prefix or suffix without a major version bump, since adding generics can break code that's relying on inference.

Inference breaking changes are usually considered acceptable (unless the fallout is terrible). Unfortunately, unlike the standard library, we can't easily fire off a crater run. Ideally, these methods would have taken `AsRef<OsStr>` from the start. Personally, I'd just go with the change and handle the fallout (unless it looks like it's going to be really bad).

As for that patch, can we not just convert to an `&OsStr` internally and use it everywhere?

**Comment by KodrAus** [comment]
> Inference breaking changes are usually considered acceptable (unless the fallout is terrible).

If you're comfortable with this then I'm on board too.

> As for that patch, can we not just convert to an `&OsStr` internally and use it everywhere?

We possibly could, but I think we would need to tweak our random filename generator a bit.

**Comment by Stebalien** [comment]
> If you're comfortable with this then I'm on board too.

I really doubt we'll run into issues here. I expect that *most* users will pass in string literals.

> We possibly could, but I think we would need to tweak our random filename generator a bit.

Probably, but that seems like the "most correct" solution.
