### ISSUE TITLE
Enhance `NamedTempFile` to allow being "destructured" into both `File` and `TempPath`

### ISSUE THREAD

**Issue by cipriancraciun** [Stebalien/tempfile#60]
Sometimes it is useful to take apart a `NamedTempFile` and obtaining both a `File` and a `TempPath` at the same time.

Currently there is `into_file` and `into_temp_path`, but either version "drops" the other one.  There is however currently a way to do this without touching this crate but in involves the `File::try_clone()` function.

(If needed I can provide the patch.)

**Comment by KodrAus** [comment]
Hi @cipriancraciun. The combination of `File` and `TempPath` effectively is a `NamedTempFile` so we could add an `into_parts` method that returned a `(File, TempPath)`. Do you have a case where you want both the handle and drop guard independently?

**Comment by cipriancraciun** [comment]
[I'm replying to this issue, but from this use-case stem all my other enhancement requests.]

@KodrAus I am currently writing a Scheme interpreter in Rust, with the main focus on systems programming.  As such I wanted to expose to my users a builtin function that could create temporary "ports" (i.e. `File` wrappers) or "paths" (i.e. `Path` wrappers).

As such I created a "builtin" function that allows the user to specify the following:
* optionally a parent in which the temporary port or path to be created;
* optionally a prefix or suffix;
* optionally (by default false) a choice to "keep" the underlying file in the filesystem for a port;

As return the user gets the port or path, and a "lock" object that can be released.  This "lock" object is nothing more than a wrapper over `TempPath`, which when "released" it just calls `close`.

Therefore I need to "break-apart" the `File` (in order to move it into my "port" wrapper), and the `TempPath` (to move it into my "lock" wrapper.)

See the following code snippet where this "destructuring" is required:  https://github.com/volution/vonuvoli-scheme/blob/925bbfa04db0ae755864a55d649d5b68247a8c38/sources/builtins_ports.rs#L1768-L1794

----

In the snippet above, one can also see the issue with not being able to "configure" the parent -- almost a third of the code is involved with it...

Regarding allowing `AsRef<OsStr>` for `prefix` and `suffix` my request stemmed from the fact that these values could be from existing path names (i.e. `Path::file_name()` or the like, which all return `OsStr`).

----

As for the `prefix` and `suffix` "sanity checks" it is because these values are under the user's control, thus the interpreter just passes them from user code to `tempfile` library.

Indeed I could make that validation in my own code, however I guess there might be other uses of these options that come directly from user controlled inputs, and not everyone would take the time and effort to verify them (or even get it correctly).

**Comment by KodrAus** [comment]
Thanks for the extra detail @cipriancraciun. Sounds like an interesting usecase! Did you want to submit a PR for an `into_parts() -> (File, TempPath)` method for this particular issue?

**Comment by Stebalien** [comment]
An alternative would be to simply expose the `path` and `file` fields. Given that `Drop` isn't defined for `NamedTempFile`, that will allow destructuring.

Con: This could be abused to construct an inconsistent NamedTempFile however, that's already possible as users can simply call `*tmp.as_mut_file() = some_file`.
Pro: Allows moving the `file` in and out of the `NamedTempFile`.
Pro: Allows us to (optionally) deprecate a bunch of methods.

**Comment by KodrAus** [comment]
@Stebalien My knee-jerk reaction to public fields is to avoid them, since we couldn't tweak the internals of `NamedTempFile` and can't maintain any cross-field invariants, but as you say since we can reassign the file anyways we're not really doing that now.

Maybe we could look at the current API for `NamedTempFile` and see what wouldn't make sense anymore with the path and handle being public? I'm guessing that would be just about every inherent method.

If we did make the fields public I think it would be good to add an additional private field, so you can still destructure a `NamedTempFile`, but can't use a struct literal to construct one:

```rust
struct NamedTempFile {
    pub path: TempPath,
    pub handle: File,
    _private: (),
}

...

let NamedTempFile { path, handle, .. } = tmp;
```

What do you think?

**Comment by Stebalien** [comment]
I have the same knee-jerk reaction however, `NamedTempFile` is really just a `(TempPath, File)` tuple with some useful deref/trait implementations. It *used* to do more then but most functionality was moved to `TempPath`.

There are some advantages to *not* adding a private field however, given that we can go from "can't be constructed" to "can be constructed" but not back, I agree that starting with a `_private` field is the way to go.

**Comment by Lucretiel** [comment]
I would rather we add the method as originally proposed than expose the underlying fields.

I have another use case for consideration: I'm working on a utility which, as part of its functionality, spawns a subprocess. I'd like to be able to attach a `NamedTempFile` to the process's stdout, and then if the process didn't exit with an error code, rename the file to the correct name. Currently I'm using `try_clone`, but getting access to the underlying file would obviously be ideal.

**Comment by cipriancraciun** [comment]
@KodrAus @Stebalien Any decision on this issue yet?  (No urgency, I was just reviewing my GitHub notifications / issues.)
