### ISSUE TITLE
Temporary directories

### ISSUE THREAD

**Issue by Stebalien** [Stebalien/tempfile#7]
Allow creating temporary directories and provide methods for securely creating/opening files under them.

**Comment by untitaker** [comment]
There seems to be https://github.com/rust-lang/tempdir for this purpose already.

**Comment by Stebalien** [comment]
I want to provide a slightly different API and some stronger security guarantees.

**Comment by Stebalien** [comment]
Done. Thank you @KodrAus for all the hard work on getting this through.

---

This ended up mostly being a merge of the tempdir crate (with interfaces matching those in this crate). I'd eventually like to provide methods for, e.g., opening a child of a temporary directory while ensuring that the child is, in fact, a child of that temporary directory (e.g., `openat`) but wrangling guarantees like this from three different platforms (modern posix (linux, freebsd, ...), technically unix (osx), and windows) is a lot of work.
