### ISSUE TITLE
Can tempfiles be read by other users on the system?

### ISSUE THREAD

**Issue by Miserlou** [Stebalien/tempfile#70]
Sorry for what might be a dumb question, but can `tempfiles` be read by other users on the same system?

**Comment by Stebalien** [comment]
They shouldn't be able to although I'm not entirely sure about windows. On unix-like systems, we create the files with a 0600 mode (read/write for the owner only). On windows, we (by default) create temporary files in the user's temporary file directory (which, IIRC, should only be readable by the user). However, if I'm not sure what the permissions would be on windows if one were to create a temporary file in a public directory.

**Comment by Miserlou** [comment]
Gotcha, that's what I wanted to know! Thanks!
