### ISSUE TITLE
Errors from creating files / directories should include the path that was attempted

### ISSUE THREAD

**Issue by luser** [Stebalien/tempfile#71]
I've been using `tempdir` in a project of mine but since that's deprecated in favor of this crate I figured I'd file this issue here.

While trying to track down [an issue in Firefox CI](https://bugzilla.mozilla.org/show_bug.cgi?id=1396845) I wound up patching `tempdir` to return the path it tried to create as part of the error message when it failed:
https://github.com/luser/tempdir/commit/bc045d5e96c85074da83efdf7ca512a2cfd5826b

Without that patch the error was just "The system cannot find the path specified. (os error 3)" which didn't give me much to work with. With that patch I instead got "Error creating temp directory "z:\\build\\build\\src\\c\\Users\\task_1537988825\\AppData\\Local\\Temp\\sccache.HQRR1j9faz6I": The system cannot find the path specified. (os error 3)" which was much more useful.

It would be nice if we could do this in the tempfile crate as well.

**Comment by Stebalien** [comment]
My concern is that the standard library never annotates errors either. On the other hand, I kind of wish it did.

Thoughts @KodrAus?

**Comment by KodrAus** [comment]
Yeh, without actually going back to look at whether we've talked about paths on `std::io::Error` before my guess is that it just doesn't support a path because not all io errors have one.

Bundling an `io::Error` with a `PathBuf` is something I always end up doing when working with `std::fs` though, so it might be worth looking at whether we want to support it here. Since everything in `tempfile` returns `io::Error`, maybe something like this?

```rust
[derive(Debug)]
struct PathError {
    path: PathBuf,
    err: io::Error,
}

impl fmt::Display for PathError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{} at path {:?}", self.err, self.path)
    }
}

impl error::Error for PathError {
    fn description(&self) -> &str {
        self.err.description()
    }
    
    fn cause(&self) -> Option<&error::Error> {
        self.err.cause()
    }
}

fn io_path(path: impl Into<PathBuf>, err: io::Error) -> io::Error {
    io::Error::new(err.kind(), PathError {
        path: path.into(),
        err,
    })
}
```

But if we want to keep `tempdir` aligned with the behaviour of `std::fs` then we probably wouldn't want to do this. I'm not sure that's really worthwhile alignment in this case though.

**Comment by luser** [comment]
The standard library mostly just propogates errors up from system APIs by error code, which is not unreasonable. I feel like we can do better. :)

**Comment by Stebalien** [comment]
Yeah, @KodrAus's proposal sounds reasonable. Would either of you be interested in implementing that?

**Comment by KodrAus** [comment]
@luser unless you'd like to take a crack at this I can put together a PR in `convert::github_promise_to_reality(this_week)`.

**Comment by luser** [comment]
I might not get to it, but I'll let you know if that changes. Feel free to [crib from my tempdir patch](https://github.com/luser/tempdir/commit/bc045d5e96c85074da83efdf7ca512a2cfd5826b) if that would be useful.
