### ISSUE TITLE
NamedTempFile without delete

### ISSUE THREAD

**Issue by rizsotto** [Stebalien/tempfile#84]
Hi, thanks for this library. It's very handy. I like that it's small and resposible for a single thing. But now I am about to ask a feature, which might not be intended to be implemented. :smile: 

I am about to implement a program which was written in Python before. Which was creating files in a given dir, with a given prefix and suffix. (But the file name contained random parts.) The files were temporary in a sense, that those were deleted by another process. The Python standard libray has the very same package (tempfile) which has the very similar type (NamedTemporaryFile). Which [allows](https://docs.python.org/2/library/tempfile.html#tempfile.NamedTemporaryFile) to disable the file removal when the handle is going out of scope.

To get this functionality, I need to reimplement most of what this crate does, but delete the `Drop` trait implementation. Or I can try to use the `persist` method, but I need to provide a random name somehow. (Not sure how to do that.)

What do you think: would that be okay to expose a `keep()` or `persist()` method on the `Builder` to ask for not to remove the file? Or how would you crate unique file names in a given directory (with given prefix and suffix)?

**Comment by Stebalien** [comment]
So, you _can_ use `std::mem::forget(tmp.into_temp_path())`. However, I agree a `keep()` method could be useful.

**Comment by rizsotto** [comment]
Thanks, I forgot about `forget`. (Bad joke probably.) Anyway, I'm glad that you like the idea of `keep`. Would you implement it, or happy to have a PR for it? Shall I close the ticket, or want you track the feature request somehow?

**Comment by davepacheco** [comment]
Would it be reasonable to support this for `TempDir` as well?  I often have a program that assembles a temporary directory in order to pack it into a tarball, and it's often useful to have a `keep` option that keeps the whole temp directory around (usually for debugging).

**Comment by Stebalien** [comment]
TempDir has an into_path method that does just that.

**Comment by davepacheco** [comment]
Thanks for that!  Sorry I missed it.
