### ISSUE TITLE
Create a temporary file in a `linux` environment

### ISSUE THREAD

**Issue by schomatis** [Stebalien/tempfile#87]
I'm not following how is the temporary file created in the `target_os = "linux"` case, the directory seems to be opened but the actual file creation (`create_unix`) seems to be invoked only in the case of an error.

I'm probably not following this correctly and this is actually a user error, I'm trying to create a file with `tempfile::tempfile()` but I'm not seeing any file being created (besides the `/tmp` directory itself being opened) in the `strace` output (it *does* work if I change to a non-`linux` setup), is there a previous configuration I'm missing?

https://github.com/Stebalien/tempfile/blob/ecce519923e895a1fca8771f1ec0e5a2ec094d95/src/file/imp/unix.rs#L61-L81

**Comment by schomatis** [comment]
I realize now that the `O_TMPFILE` is being used, so either there's something wrong with my setup or the file itself is being created and I'm not detecting it, I'll check again more carefully and report back.

**Comment by Stebalien** [comment]
If you call `tempfile::tempfile()`, we'll create a temporary file that _never_ appears in the filesystem. This is useful for offloading data to disk, sharing data between processes using file descriptors, etc. If you need a _named_ temporary file, you'll need to call `tempfile::NamedTempFile::new()`.

**Comment by schomatis** [comment]
Makes sense, thanks for the clarification.
