### ISSUE TITLE
Old documentation on homepage

### ISSUE THREAD

**Issue by ArekPiekarz** [Stebalien/tempfile#88]
#### Summary
The Documentation link on this crate's [Homepage](https://stebalien.com/projects/tempfile-rs/) leads to an old version - http://stebalien.github.io/tempfile/tempfile/.
The exact one is not specified there, although it's definitely before v3.0.0, meaning at least from 1.5 year ago.

#### How to stumble upon it
You may think it's hard to find the outdated docs, but it's quite the contrary. I wanted a way to create a temporary directory in Rust, so I searched on crates.io. I found [tempdir](https://crates.io/crates/tempdir), but it declared deprecation in favor of tempfile. I then went to [its page](https://crates.io/crates/tempfile/) on crates.io, clicked on [Homepage](https://stebalien.com/projects/tempfile-rs/) (notice it's the first link under the title), then on [Documentation](http://stebalien.github.io/tempfile/tempfile/) (again the first link). I was really confused when it didn't contain any method for creating temporary directories.

**Comment by Stebalien** [comment]
Thanks for catching that! The link should now be fixed (once it redeploys).
