### ISSUE TITLE
PathPersistError is private

### ISSUE THREAD

**Issue by ony** [Stebalien/tempfile#89]
Similar to #25 this impacts documentation and ability to write something like:

```
pub fn commit(self) -> Result<(), _> {                              
  self.temp.into_temp_path().persist(self.path) 
  // found type `std::result::Result<_, tempfile::file::PathPersistError>`
}
```

Though I'd prefer to stick with `std::io::Result` here to have it symmetrical with `NamedTempFile::new_in()`.

**Comment by Stebalien** [comment]
Fixed in #90 (although I tagged the wrong issue). Released in 3.0.8.
