### ISSUE TITLE
use of unstable library feature

### ISSUE THREAD

**Issue by nihakue** [Stebalien/tempfile#9]
After I fixed the create_unix typo, compiling gives me this error on mac OSX: 

    Nadecinogut:tempfile gabriel$ cargo build
    Compiling tempfile v0.5.0 (file:///Users/gabriel/Code/rust/tempfile)
    src/imp/unix.rs:26:27: 26:49 error: use of unstable library feature 'from_raw_os': recent addition to std::os::unix::io
    src/imp/unix.rs:26         fd => Ok(unsafe { FromRawFd::from_raw_fd(fd) }),
                                             ^~~~~~~~~~~~~~~~~~~~~~
    src/imp/unix.rs:105:29: 105:51 error: use of unstable library feature 'from_raw_os': recent addition to std::os::unix::io
    src/imp/unix.rs:105                 let first = FromRawFd::from_raw_fd(fd);
                                                ^~~~~~~~~~~~~~~~~~~~~~
    error: aborting due to 2 previous errors
    Could not compile `tempfile`.

My Rust isn't good enough to go in and fix this, or I would. Do you know what might be happening here?

**Comment by Stebalien** [comment]
It's not compatible with the current stable release. However, it will be compatible with 1.1 (currently in beta) which should be released in about a month.
-- 
Steven Allen

**Comment by nihakue** [comment]
Can tempfile be used at all in 1.0.0? I'm brand new to the language, and not able to find a compiler flag that allows unstable features (or even what is meant by that).

**Comment by Stebalien** [comment]
No. Sorry, I could theoretically make a subset of the current functionality available on 1.0 but it's not really worth the effort. For now, I recommend you use 1.1 beta.

**Comment by nihakue** [comment]
I understand. :+1:

**Comment by brookst** [comment]
I'm also seeing this with the 1.1 beta:

       Compiling tempfile v0.2.0
    /home/brooks/.cargo/registry/src/github.com-1ecc6299db9ec823/tempfile-0.2.0/src/lib.rs:1:1: 1:34 error: unstable feature
    /home/brooks/.cargo/registry/src/github.com-1ecc6299db9ec823/tempfile-0.2.0/src/lib.rs:1 #![feature(convert, from_raw_os)]
                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    note: this feature may not be used in the beta release channel
    error: aborting due to previous error
    Build failed, waiting for other jobs to finish...
    Could not compile `tempfile`.
    
    > cargo --version
    cargo 0.2.0-nightly (a483581 2015-05-14) (built 2015-05-15)
    > rustc --version
    rustc 1.1.0-beta (cd7d89af9 2015-05-16) (built 2015-05-16)

Can these feature gates really be used in the beta, or do they only work in the nightly?

Thanks.

**Comment by Stebalien** [comment]
You're version is out of date. The current version is 0.5.1.

**Comment by brookst** [comment]
Ah yes, a `cargo update` and I have 0.5.1 - sorry for the silly question!

**Comment by Stebalien** [comment]
Np.
