### ISSUE TITLE
Document independent temporary file access

### ISSUE THREAD

**Issue by aztecrex** [Stebalien/tempfile#91]
Documentation should give an example of how to have multiple independent references to a temporary file.

The project descriptions says "...this library also allows users to securely open multiple independent references to the same temporary file..." There isn't an example and it isn't obvious how the API supports it.

**Comment by Stebalien** [comment]
The function is https://docs.rs/tempfile/3.0.8/tempfile/struct.NamedTempFile.html#method.reopen but yeah, an example would be nice.

**Comment by aztecrex** [comment]
Thanks.I didn't look to that struct because the documentation says that it is not the secure way to share a temporary file.  

However, the documentation says that the `File` returned by `tempfile` is deleted after the last file handle is closed. The way I read it, that `tempfile` provides the secure, shareable mechanism. However, I do not see how to obtain multiple independent handles to a file created that way.

Likely I am misinterpreting the documentation. Once I understand what's going on, I am happy to supply documentation changes including examples.

**Comment by Stebalien** [comment]
> Thanks.I didn't look to that struct because the documentation says that it is not the secure way to share a temporary file.

It does? There are some general security issues with named temp files but reopening should always be safe.

> The way I read it, that tempfile provides the secure, shareable mechanism. However, I do not see how to obtain multiple independent handles to a file created that way.

Unfortunately, there's no cross-platform way to do this. Specifically, there's no way to reopen a deleted file on macos.

**Comment by aztecrex** [comment]
Under "Security:" _This variant is NOT secure/reliable in the presence of a pathological temporary file cleaner._ . 

Is that statement true? It kept me digging into the `tempfile` function rather than looking at `NamedTempFile` to get the secure multi-handle behavior described in the project README. If `NamedTempFile` can be used securely for some purposes, perhaps, in place of that statement, the docs could describe the use or conditions under which it can be used securely.

For `tempfile`, Maybe the docs should either not say anything about multiple file handles.  Or maybe show how it can be done on some OSs--mentioning the known limitation on some OSs/Mac.

**Comment by Stebalien** [comment]
> Is that statement true?

Hm. Those docs used to be significantly more verbose but we cut them back. I'll expand on them a bit.
