### ISSUE TITLE
Allow tempfile to be opened in append mode.

### ISSUE THREAD

**Issue by xavierd** [Stebalien/tempfile#93]
I've recently needed to be able to always write to the end of the file, and it looks like the crate doesn't provide a way to pass the O_APPEND flag to the underlying open call.

Overall, it almost looks like supporting std::fs::OpenOptions in Builder would help fix this, and maybe #30 in a generic fashion.

**Comment by Stebalien** [comment]
Adding an `append` function to the builder would probably do this. I wouldn't add support for _all_ of `OpenOptions` as, e.g., `write` doesn't really make sense (opening a temporary file read-only isn't useful).
